spring:
  datasource:
    url: jdbc:mysql://localhost:3306/posting
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# values
jwt:
  password: secretKey