spring:
  datasource:
    url: jdbc:mysql://localhost:3306/posting
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: tkddn3367@gmail.com
    password: password
    properties:
      smtp:
        auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true

# values
jwt:
  password: secretKey