spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true